// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ace.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Openiap {

  /// <summary>Holder for reflection information generated from ace.proto</summary>
  public static partial class AceReflection {

    #region Descriptor
    /// <summary>File descriptor for ace.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CglhY2UucHJvdG8SB29wZW5pYXAiMAoDQWNlEgsKA19pZBgBIAEoCRIMCgRk",
            "ZW55GAIgASgIEg4KBnJpZ2h0cxgDIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Openiap.Ace), global::Openiap.Ace.Parser, new[]{ "Id", "Deny", "Rights" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Ace : pb::IMessage<Ace> {
    private static readonly pb::MessageParser<Ace> _parser = new pb::MessageParser<Ace>(() => new Ace());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Ace> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Openiap.AceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Ace() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Ace(Ace other) : this() {
      Id_ = other.Id_;
      deny_ = other.deny_;
      rights_ = other.rights_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Ace Clone() {
      return new Ace(this);
    }

    /// <summary>Field number for the "_id" field.</summary>
    public const int IdFieldNumber = 1;
    private string Id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return Id_; }
      set {
        Id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "deny" field.</summary>
    public const int DenyFieldNumber = 2;
    private bool deny_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Deny {
      get { return deny_; }
      set {
        deny_ = value;
      }
    }

    /// <summary>Field number for the "rights" field.</summary>
    public const int RightsFieldNumber = 3;
    private int rights_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Rights {
      get { return rights_; }
      set {
        rights_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Ace);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Ace other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Deny != other.Deny) return false;
      if (Rights != other.Rights) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Deny != false) hash ^= Deny.GetHashCode();
      if (Rights != 0) hash ^= Rights.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Deny != false) {
        output.WriteRawTag(16);
        output.WriteBool(Deny);
      }
      if (Rights != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Rights);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Deny != false) {
        size += 1 + 1;
      }
      if (Rights != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rights);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Ace other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Deny != false) {
        Deny = other.Deny;
      }
      if (other.Rights != 0) {
        Rights = other.Rights;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Deny = input.ReadBool();
            break;
          }
          case 24: {
            Rights = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
